#!/usr/bin/python

#Photostory 1.0 - Reminder
#by Joel Auterson (joel.auterson@googlemail.com)
#http://www.launchpad.net/photostory

import os.path
import time
import pynotify

time.sleep(10)

year = time.localtime()[0]
month = time.localtime()[1]
day = time.localtime()[2]

if (month < 10):
    month = "0" + str(month)
if (day < 10):
    day = "0" + str(day)

dateString = str(year) + "-" + str(month) + "-" + str(day)

if os.path.exists(os.path.expanduser('~/.photostory/photos/') + dateString + ".png"):
    print 'File exists.'
else:
    print 'File does not exist.'
    uri = "file://" + os.path.abspath(os.path.curdir) + "/photostory.svg"

    n = pynotify.Notification("Photostory", "You haven't taken a picture today!", uri)
    n.show()
